Rh/Models/Instructor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.Course = new HashSet<Course>();
        }
    
        public int ID_INSTRUCTOR { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string TIPO { get; set; }
        public string COMPANIA { get; set; }
        public string REGISTRO_STP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course { get; set; }
    }
}

Rh/Controllers/InstructorController.cs
using Rh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rh.Controllers
{
    public class InstructorController : Controller
    {
        [HttpGet]
        public ActionResult CrearInstructores()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CrearInstructores(string nombreCompleto, string compania, string stp, string tipo)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Instructor inst = new Instructor();
                inst.NOMBRE_COMPLETO = nombreCompleto;
                inst.COMPANIA = compania;
                inst.REGISTRO_STP = stp;
                inst.TIPO = tipo;
                db.Instructor.Add(inst);
                db.SaveChanges();
                return RedirectToAction("VerInstructores");
            }
        }

        [HttpGet]
        public ActionResult VerInstructores()
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                var Instructores = db.Instructor.OrderBy(x => x.ID_INSTRUCTOR).ToList();
                return View(Instructores);
            }
        }

        [HttpGet]
        public ActionResult EliminarInstructor(int id)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Instructor inst = db.Instructor.Find(id);
                db.Instructor.Remove(inst);
                db.SaveChanges();
                return RedirectToAction("VerInstructores");
            }
        }

        [HttpGet]
        public ActionResult EditarInstructor(int id)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Instructor inst = db.Instructor.Find(id);
                return View(inst);
            }
        }

        [HttpPost]
        public ActionResult EditarInstructor(int ID_INSTRUCTOR, string nombreCompleto, string compania, string stp, string tipo)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Instructor insta = db.Instructor.Find(ID_INSTRUCTOR);
                insta.NOMBRE_COMPLETO = nombreCompleto;
                insta.COMPANIA = compania;
                insta.REGISTRO_STP = stp;
                insta.TIPO = tipo;
                db.SaveChanges();
                return RedirectToAction("VerInstructores");
            }
        }

    }
}

Rh/Views/Instructor/CrearInstructores.cshtml
@using (Html.BeginForm("CrearInstructores", "Instructor"))
{
    <div class="form-horizontal">
        <h1>Crear Instructor</h1>
        <h4 style="color:#0094ff;"><strong>Favor de introducir la información solicitada</strong></h4>
        <hr>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Nombre">Nombre Completo</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="nombreCompleto" required="required" type="text" />
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Tipo">Tipo</label>
            <div class="col-md-9">
                <select class="form-control" id="tipo" name="tipo" required="required" onchange="habilitar()">
                    <option value="">Selecciona el tipo</option>
                    <option value="Interno">Interno</option>
                    <option value="Externo">Externo</option>
                    <option value="Otro">Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="Tipo" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="compania">Compañía</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="compania" id="compania" required="required" type="text" />
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="stp">STP</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="stp" id="stp" required="required" type="text" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success">
            </div>
        </div>

    </div>
}
<script type="text/javascript">
    function habilitar() {
        let tipo = document.getElementById("tipo");
        let compania = document.getElementById("compania");
        let stp = document.getElementById("stp");

        if (tipo.value == "Externo" || tipo.value == "Otro") {
            compania.value = "";
            stp.disabled = false;
        }
        else {
            if (tipo.value == "Interno") {
                compania.value = "JCI";
                stp.disabled = true;
            }
        }
    }
</script>

Rh/Views/Instructor/EditarInstructor.cshtml
@model Rh.Models.Instructor

@{
    ViewBag.Title = "Editar Instructor";
}

<h2>Editar Instructor</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>Instructor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.ID_INSTRUCTOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ID_INSTRUCTOR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_INSTRUCTOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Nombre">Nombre Completo</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" id="nombreCompleto" name="nombreCompleto" required="required" type="text" />
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.NOMBRE_COMPLETO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE_COMPLETO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE_COMPLETO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Tipo">Tipo</label>
            <div class="col-md-9">
                <select class="form-control" id="tipo" name="tipo" required="required" onchange="habilitar()">
                    <option value="Interno">Interno</option>
                    <option value="Externo">Externo</option>
                    <option value="Otro">Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="Tipo" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.TIPO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIPO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TIPO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="compania">Compañía</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="compania" id="compania" required="required" type="text" />
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.COMPANIA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COMPANIA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COMPANIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="stp">STP</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="stp" id="stp" required="required" type="text" />
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.REGISTRO_STP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.REGISTRO_STP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.REGISTRO_STP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "VerInstructores")
</div>

<script type="text/javascript">

    let nombreModel = document.getElementById("NOMBRE_COMPLETO").value;
    let tipoModel = document.getElementById("TIPO").value;
    let companiaModel = document.getElementById("COMPANIA").value;
    let stpModel = document.getElementById("REGISTRO_STP").value;

    let nombre = document.getElementById("nombreCompleto");
    let tipo = document.getElementById("tipo");
    let compania = document.getElementById("compania");
    let stp = document.getElementById("stp");

    nombre.value = nombreModel;
    tipo.value = tipoModel;
    compania.value = companiaModel;
    stp.value = stpModel;

    if (tipo.value == "Interno") {
        habilitar();
    }

    function habilitar() {
        let tipo = document.getElementById("tipo");
        let compania = document.getElementById("compania");
        let stp = document.getElementById("stp");

        if (tipo.value == "Externo" || tipo.value == "Otro") {
            compania.value = "";
            stp.disabled = false;
        }
        else {
            if (tipo.value == "Interno") {
                compania.value = "JCI";
                stp.disabled = true;
                stp.value = "";
            }
        }
    }

</script>

Rh/Views/Instructor/VerInstructores.cshtml
@model IEnumerable<Rh.Models.Instructor>

@{
    ViewBag.Title = "VerInstructores";
}

<h2>Instructores</h2>

<h4 style="color:#0094ff;">
    <strong> @Html.ActionLink("Crear", "CrearInstructores")</strong>
</h4>
<table class="table">
    <tr>
        <th>
            <!-- @Html.DisplayNameFor(model => model.ID_INSTRUCTOR) -->
            ID
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.NOMBRE_COMPLETO) -->
            NOMBRE
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIPO)
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.COMPANIA) -->
            COMPAÑÍA
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.REGISTRO_STP) -->
            REGISTRO STP
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID_INSTRUCTOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NOMBRE_COMPLETO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TIPO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.COMPANIA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.REGISTRO_STP)
            </td>
            <td>
                <h5 style="color:#0094ff;">
                    @Html.ActionLink("Editar", "EditarInstructor", new { id = item.ID_INSTRUCTOR }) |
                    @Html.ActionLink("Eliminar", "EliminarInstructor", new { id = item.ID_INSTRUCTOR })
                </h5>
            </td>
        </tr>
    }

</table>