Rh/Models/Course.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Employee_Course = new HashSet<Employee_Course>();
        }
    
        public int ID_CURSO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> DURACION { get; set; }
        public Nullable<int> CALIFICACION_MIN { get; set; }
        public string TIPO_CURSO { get; set; }
        public string CLASIFICACION { get; set; }
        public string AREA_TEMATICA { get; set; }
        public string AREA_APLICACION { get; set; }
        public string OBJETIVO { get; set; }
        public string MODALIDAD { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> ID_INSTRUCTOR { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Course> Employee_Course { get; set; }
    }
}

Rh/Controllers/CourseController.cs
using Rh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rh.Controllers
{
    public class CourseController : Controller
    {
        public List<Instructor> Instructores { get; set; }

        [HttpGet]
        public ActionResult CrearCurso()
        {
            return View(Instructores);
        }

        [HttpPost]
        public ActionResult CrearCurso(
            string nombre,
            int duracion,
            int calificacion,
            string tipo,
            string clasificacion,
            string areaTematica,
            string areaAplicacion,
            string objetivo,
            string modalidad,
            string comentarios,
            int instructor
        )
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Course cur = new Course();
                cur.NOMBRE = nombre;
                cur.DURACION = duracion;
                cur.CALIFICACION_MIN = calificacion;
                cur.TIPO_CURSO = tipo;
                cur.CLASIFICACION = clasificacion;
                cur.AREA_TEMATICA = areaTematica;
                cur.AREA_APLICACION = areaAplicacion;
                cur.OBJETIVO = objetivo;
                cur.MODALIDAD = modalidad;
                cur.COMENTARIOS = comentarios;
                cur.ID_INSTRUCTOR = instructor;
                db.Course.Add(cur);
                db.SaveChanges();
                return RedirectToAction("VerCursos");
            }
        }

        [HttpGet]
        public ActionResult VerCursos()
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                var Cursos = db.Course.OrderBy(x => x.ID_CURSO).ToList();
                return View(Cursos);
            }
        }

        [HttpGet]
        public ActionResult EliminarCurso(int id)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Course cur = db.Course.Find(id);
                db.Course.Remove(cur);
                db.SaveChanges();
                return RedirectToAction("VerCursos");
            }
        }

        [HttpGet]
        public ActionResult EditarCurso(int id)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Course cur = db.Course.Find(id);
                return View(cur);
            }
        }

        [HttpPost]
        public ActionResult EditarCurso(
            int ID_CURSO,
            string nombre,
            int duracion,
            int calificacion,
            string tipo,
            string clasificacion,
            string areaTematica,
            string areaAplicacion,
            string objetivo,
            string modalidad,
            string comentarios,
            int instructor
        )
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Course cur = db.Course.Find(ID_CURSO);
                cur.NOMBRE = nombre;
                cur.DURACION = duracion;
                cur.CALIFICACION_MIN = calificacion;
                cur.TIPO_CURSO = tipo;
                cur.CLASIFICACION = clasificacion;
                cur.AREA_TEMATICA = areaTematica;
                cur.AREA_APLICACION = areaAplicacion;
                cur.OBJETIVO = objetivo;
                cur.MODALIDAD = modalidad;
                cur.COMENTARIOS = comentarios;
                cur.ID_INSTRUCTOR = instructor;
                db.SaveChanges();
                return RedirectToAction("VerCursos");
            }
        }
    }
}

Rh/Controllers/EmployeeCourseController.cs
using Rh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rh.Controllers
{
    public class EmployeeCourseController : Controller
    {
        List<Employee_Course> Induccion = new List<Employee_Course>
    {
            new Employee_Course{ ID_CURSO = 3, CALIFICACION = 100},
            new Employee_Course{ ID_CURSO = 4, CALIFICACION = 100},
            new Employee_Course{ ID_CURSO = 5, CALIFICACION = 100},
            new Employee_Course{ ID_CURSO = 6, CALIFICACION = 100},
    };

        List<Employee_Course> Calidad = new List<Employee_Course>
    {
            new Employee_Course{ ID_CURSO = 1, CALIFICACION = 100},
            new Employee_Course{ ID_CURSO = 2, CALIFICACION = 100},
            new Employee_Course{ ID_CURSO = 8, CALIFICACION = 100},
            new Employee_Course{ ID_CURSO = 9, CALIFICACION = 100},
    };

        [HttpGet]
        public ActionResult AsignarCursos()
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult AsignarCursos(int? idCurso, int numReloj, string nombrePaquete)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Employee_Course empCur = new Employee_Course();
                var empleado = db.Employee.Where(x => x.EmployeeID == numReloj).ToList();
                DateTime now = DateTime.Now;

                if (idCurso == null)
                {
                    switch (nombrePaquete)
                    {
                        case "Induccion":
                            foreach (var item in Induccion)
                            {
                                empCur.ID_CURSO = item.ID_CURSO;
                                empCur.CALIFICACION = item.CALIFICACION;
                                empCur.ID_EMPLEADO = empleado[0].ID;
                                empCur.FECHA = now;
                                db.Employee_Course.Add(empCur);
                                db.SaveChanges();
                            }
                            break;
                        case "Calidad":
                            foreach (var item in Calidad)
                            {
                                empCur.ID_CURSO = item.ID_CURSO;
                                empCur.CALIFICACION = item.CALIFICACION;
                                empCur.ID_EMPLEADO = empleado[0].ID;
                                empCur.FECHA = now;
                                db.Employee_Course.Add(empCur);
                                db.SaveChanges();
                            }
                            break;
                        default:
                            //curso inexistente
                            break;
                    }
                }
                else
                {
                    empCur.ID_CURSO = idCurso;
                    empCur.ID_EMPLEADO = empleado[0].ID;
                    empCur.FECHA = now;
                    db.Employee_Course.Add(empCur);
                    db.SaveChanges();
                }
                return View();
            }
        }

        [HttpGet]
        public ActionResult BuscarCursosEmpleado()
        {
            return View();
        }

        [HttpPost]
        public ActionResult VerCursosEmpleado(int numReloj)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                var empleado = db.Employee.Where(x => x.EmployeeID == numReloj).ToList();
                var idEmpleado = empleado[0].ID;
                var empleado_curso = db.Employee_Course.Where(x => x.ID_EMPLEADO == idEmpleado).ToList();
                return View(empleado_curso);
            }
        }

        [HttpGet]
        public ActionResult EliminarCursoEmpleado(int id)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Employee_Course empCur = db.Employee_Course.Find(id);
                db.Employee_Course.Remove(empCur);
                db.SaveChanges();
                return RedirectToAction("BuscarCursosEmpleado");
            }
        }

        [HttpGet]
        public ActionResult Calificaciones()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AsignarCalificacion(int id)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Employee_Course empCur = db.Employee_Course.Find(id);
                db.SaveChanges();
                return View(empCur);
            }
        }

        [HttpPost]
        public ActionResult AsignarCalificacion(Employee_Course x)
        {
            using (RecursosHumanosContext db = new RecursosHumanosContext())
            {
                Employee_Course empCurso = db.Employee_Course.Find(x.ID_EMPLEADO_CURSO);
                empCurso.CALIFICACION = x.CALIFICACION;
                db.SaveChanges();
                return RedirectToAction("BuscarCursosEmpleado");
            }
        }
    }
}

Rh/Views/Course/CrearCurso.cshtml
@using (Html.BeginForm("CrearCurso", "Course"))
{
    <div class="form-horizontal">
        <h1>Crear Curso</h1>
        <h4 style="color:#0094ff;"><strong>Favor de introducir la información solicitada</strong></h4>
        <hr>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Nombre">Nombre</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="nombre" required="required" type="text" />
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Duración">Duración</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="duracion" required="required" type="number" />
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Calificación Mínima">Calificación Mínima</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="calificacion" required="required" type="number" />
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Tipo">Tipo</label>
            <div class="col-md-9">
                <select class="form-control" name="tipo" required="required">
                    <option>Interno</option>
                    <option>Externo</option>
                    <option>Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="Tipo" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Clasificación">Clasificación</label>
            <div class="col-md-9">
                <select class="form-control" name="clasificacion" required="required">
                    <option>Sin clasificación</option>
                    <option>Actitud</option>
                    <option>Diagnóstico</option>
                    <option>Externos</option>
                    <option>Habilidad</option>
                    <option>Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="Clasificación" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Área temática">Área temática</label>
            <div class="col-md-9">
                <select class="form-control" name="areaTematica" required="required">
                    <option>Producción general</option>
                    <option>Servicios</option>
                    <option>Administración, contabilidad y economía</option>
                    <option>Comercialización</option>
                    <option>Manteniminto y reparación</option>
                    <option>Desarrollo personal y familiar</option>
                    <option>Uso de las tecnologías de la información</option>
                    <option>Seguridad</option>
                    <option>Participación social</option>
                    <option>Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="areaTematica" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Área aplicación">Área aplicación</label>
            <div class="col-md-9">
                <select class="form-control" name="areaAplicacion" required="required">
                    <option>Producción</option>
                    <option>Calidad</option>
                    <option>Ingenería</option>
                    <option>Mantenimiento</option>
                    <option>Almacén</option>
                    <option>Tool crib</option>
                    <option>Tool room</option>
                    <option>Recursos humanos</option>
                    <option>Seguridad</option>
                    <option>Cafetería</option>
                    <option>Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="areaAplicacion" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Objetivo">Objetivo</label>
            <div class="col-md-9">
                <select class="form-control" name="objetivo" required="required">
                    <option>Actulizar y mejorar conocimiento</option>
                    <option>Proporcionar información de nuevas técnicas</option>
                    <option>Preparar para ocupar puestos o vacantes</option>
                    <option>Prevenir riegos de trabajo</option>
                    <option>Incrementar la productividad</option>
                    <option>Otro</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="objetivo" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Modalidad">Modalidad</label>
            <div class="col-md-9">
                <select class="form-control" name="modalidad" required="required">
                    <option>Presencial</option>
                    <option>Virtual</option>
                    <option>Mixta</option>
                </select>
                <span class="field-validation-valid text-danger" data-valmsg-for="modalidad" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Comentarios">Comentarios</label>
            <div class="col-md-9">
                <textarea class="form-control text-box single-line" name="comentarios" type="text" placeholder="Describir los casos en los que puso 'Otros' o decir cosas adicionales"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label class="control-label col-md-3" for="Instructor">Instructor</label>
            <div class="col-md-9">
                <input class="form-control text-box single-line" name="instructor" required="required" type="number" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success">
            </div>
        </div>

    </div>
}

Rh/Views/Course/VerCursos.cshtml
@model IEnumerable<Rh.Models.Course>

@{
    ViewBag.Title = "Cursos";
}

<h2>Cursos</h2>

<h4 style="color:#0094ff;">
    <strong> @Html.ActionLink("Crear", "CrearCurso")</strong>
</h4>
<h4 style="color:#0094ff;">
    <strong> @Html.ActionLink("Asignar Cursos", "AsignarCursos", "EmployeeCourse")</strong>
</h4>
<h4 style="color:#0094ff;">
    <strong> @Html.ActionLink("Buscar Curso Empleado", "BuscarCursosEmpleado", "EmployeeCourse")</strong>
</h4>
<table class="table">
    <tr>
        <th>
            <!-- @Html.DisplayNameFor(model => model.ID_CURSO) -->
            ID
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.DURACION) -->
            DURACIÓN
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.CALIFICACION_MIN) -->
            CALIFICACIÓN MÍN
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.TIPO_CURSO) -->
            TIPO
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.CLASIFICACION) -->
            CLASIFICACIÓN
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.AREA_TEMATICA) -->
            ÁREA TEMÁTICA
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.AREA_APLICACION) -->
            ÁREA DE APLICACIÓN
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OBJETIVO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MODALIDAD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMENTARIOS)
        </th>
        <th>
            <!-- @Html.DisplayNameFor(model => model.ID_INSTRUCTOR) -->
            INSTRUCTOR
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID_CURSO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NOMBRE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DURACION)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CALIFICACION_MIN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TIPO_CURSO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CLASIFICACION)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AREA_TEMATICA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AREA_APLICACION)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OBJETIVO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MODALIDAD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.COMENTARIOS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ID_INSTRUCTOR)
            </td>
            <td>
                <h5 style="color:#0094ff;">
                    @Html.ActionLink("Editar", "EditarCurso", new { id = item.ID_CURSO })
                    @Html.ActionLink("Eliminar", "EliminarCurso", new { id = item.ID_CURSO })
                </h5>
            </td>
        </tr>
    }

</table>